export const CATEGORIES = [
  {
    name: "מסעדות ואוכל",
    name_en: "restaurants",
    slug: "restaurants",
    icon: "🍽️",
    subcategories: [
      { name: "מסעדות", name_en: "restaurants", slug: "restaurants-dining" },
      { name: "בתי קפה", name_en: "cafes", slug: "cafes" },
      { name: "פיצריות", name_en: "pizza", slug: "pizza" },
      { name: "סושי", name_en: "sushi", slug: "sushi" },
      { name: "בשרי", name_en: "meat", slug: "meat" },
      { name: "טבעוני / צמחוני", name_en: "vegan", slug: "vegan" },
      { name: "מאפיות", name_en: "bakeries", slug: "bakeries" },
      { name: "משלוחי אוכל", name_en: "delivery", slug: "food-delivery" },
      { name: "קייטרינג", name_en: "catering", slug: "catering" },
      { name: "ברים ופאבים", name_en: "bars", slug: "bars" },
      { name: "גלידריות", name_en: "ice-cream", slug: "ice-cream" },
      { name: "מזון מהיר", name_en: "fast-food", slug: "fast-food" },
    ],
  },
  {
    name: "בריאות ורפואה",
    name_en: "health",
    slug: "health",
    icon: "🏥",
    subcategories: [
      { name: "רופאי שיניים", name_en: "dentists", slug: "dentists" },
      { name: "רופאי עיניים", name_en: "eye-doctors", slug: "eye-doctors" },
      { name: "רופאי משפחה", name_en: "family-doctors", slug: "family-doctors" },
      { name: "פסיכולוגים", name_en: "psychologists", slug: "psychologists" },
      { name: "פיזיותרפיה", name_en: "physiotherapy", slug: "physiotherapy" },
      { name: "בתי מרקחת", name_en: "pharmacies", slug: "pharmacies" },
      { name: "מרפאות", name_en: "clinics", slug: "clinics" },
      { name: "אורתודנטים", name_en: "orthodontists", slug: "orthodontists" },
      { name: "רפואה משלימה", name_en: "alternative-medicine", slug: "alternative-medicine" },
    ],
  },
  {
    name: "יופי וטיפוח",
    name_en: "beauty",
    slug: "beauty",
    icon: "💇",
    subcategories: [
      { name: "מספרות", name_en: "hair-salons", slug: "hair-salons" },
      { name: "מכוני יופי", name_en: "beauty-salons", slug: "beauty-salons" },
      { name: "ציפורניים", name_en: "nails", slug: "nails" },
      { name: "ברברים", name_en: "barbers", slug: "barbers" },
      { name: "ספא ועיסוי", name_en: "spa", slug: "spa" },
      { name: "קוסמטיקה", name_en: "cosmetics", slug: "cosmetics" },
      { name: "הסרת שיער", name_en: "hair-removal", slug: "hair-removal" },
    ],
  },
  {
    name: "רכב",
    name_en: "automotive",
    slug: "automotive",
    icon: "🚗",
    subcategories: [
      { name: "מוסכים", name_en: "garages", slug: "garages" },
      { name: "סוכנויות רכב", name_en: "car-dealers", slug: "car-dealers" },
      { name: "חלקי חילוף", name_en: "car-parts", slug: "car-parts" },
      { name: "שטיפת רכב", name_en: "car-wash", slug: "car-wash" },
      { name: "פנצ׳ריות", name_en: "tires", slug: "tires" },
      { name: "ביטוח רכב", name_en: "car-insurance", slug: "car-insurance" },
      { name: "השכרת רכב", name_en: "car-rental", slug: "car-rental" },
      { name: "גרירה", name_en: "towing", slug: "towing" },
    ],
  },
  {
    name: "בית וגינה",
    name_en: "home",
    slug: "home",
    icon: "🏠",
    subcategories: [
      { name: "שיפוצים", name_en: "renovation", slug: "renovation" },
      { name: "אינסטלציה", name_en: "plumbing", slug: "plumbing" },
      { name: "חשמלאים", name_en: "electricians", slug: "electricians" },
      { name: "מנעולנים", name_en: "locksmiths", slug: "locksmiths" },
      { name: "ניקיון", name_en: "cleaning", slug: "cleaning" },
      { name: "רהיטים", name_en: "furniture", slug: "furniture" },
      { name: "גינון", name_en: "gardening", slug: "gardening" },
      { name: "מיזוג אוויר", name_en: "ac", slug: "air-conditioning" },
      { name: "הדברה", name_en: "pest-control", slug: "pest-control" },
      { name: "הובלות", name_en: "moving", slug: "moving" },
    ],
  },
  {
    name: "חינוך ולימודים",
    name_en: "education",
    slug: "education",
    icon: "📚",
    subcategories: [
      { name: "בתי ספר", name_en: "schools", slug: "schools" },
      { name: "גני ילדים", name_en: "kindergartens", slug: "kindergartens" },
      { name: "שיעורים פרטיים", name_en: "tutoring", slug: "tutoring" },
      { name: "קורסים", name_en: "courses", slug: "courses" },
      { name: "אוניברסיטאות", name_en: "universities", slug: "universities" },
      { name: "לימודי שפות", name_en: "languages", slug: "languages" },
      { name: "מכינות", name_en: "prep-courses", slug: "prep-courses" },
    ],
  },
  {
    name: "קניות",
    name_en: "shopping",
    slug: "shopping",
    icon: "🛍️",
    subcategories: [
      { name: "סופרמרקטים", name_en: "supermarkets", slug: "supermarkets" },
      { name: "אופנה וביגוד", name_en: "fashion", slug: "fashion" },
      { name: "אלקטרוניקה", name_en: "electronics", slug: "electronics" },
      { name: "חנויות נוחות", name_en: "convenience", slug: "convenience" },
      { name: "צעצועים", name_en: "toys", slug: "toys" },
      { name: "ספרים", name_en: "books", slug: "books" },
      { name: "תכשיטים", name_en: "jewelry", slug: "jewelry" },
      { name: "פרחים", name_en: "flowers", slug: "flowers" },
      { name: "חיות מחמד", name_en: "pets", slug: "pets" },
    ],
  },
  {
    name: "שירותים מקצועיים",
    name_en: "professional-services",
    slug: "professional-services",
    icon: "💼",
    subcategories: [
      { name: "עורכי דין", name_en: "lawyers", slug: "lawyers" },
      { name: "רואי חשבון", name_en: "accountants", slug: "accountants" },
      { name: "יועצי מס", name_en: "tax-advisors", slug: "tax-advisors" },
      { name: "ביטוח", name_en: "insurance", slug: "insurance" },
      { name: "נדל״ן", name_en: "real-estate", slug: "real-estate" },
      { name: "אדריכלות", name_en: "architecture", slug: "architecture" },
      { name: "שמאות", name_en: "appraisals", slug: "appraisals" },
      { name: "תרגום ונוטריון", name_en: "translation", slug: "translation" },
    ],
  },
  {
    name: "פנאי ובידור",
    name_en: "entertainment",
    slug: "entertainment",
    icon: "🎭",
    subcategories: [
      { name: "חדרי בריחה", name_en: "escape-rooms", slug: "escape-rooms" },
      { name: "קולנוע", name_en: "cinema", slug: "cinema" },
      { name: "חוגים", name_en: "classes", slug: "classes" },
      { name: "אירועים", name_en: "events", slug: "events" },
      { name: "אטרקציות", name_en: "attractions", slug: "attractions" },
      { name: "מועדוני לילה", name_en: "nightclubs", slug: "nightclubs" },
      { name: "בריכות שחיה", name_en: "pools", slug: "pools" },
    ],
  },
  {
    name: "ספורט וכושר",
    name_en: "fitness",
    slug: "fitness",
    icon: "💪",
    subcategories: [
      { name: "חדרי כושר", name_en: "gyms", slug: "gyms" },
      { name: "יוגה ופילאטיס", name_en: "yoga", slug: "yoga" },
      { name: "אומנויות לחימה", name_en: "martial-arts", slug: "martial-arts" },
      { name: "חנויות ספורט", name_en: "sports-shops", slug: "sports-shops" },
      { name: "מאמנים אישיים", name_en: "personal-trainers", slug: "personal-trainers" },
    ],
  },
  {
    name: "תיירות ונסיעות",
    name_en: "travel",
    slug: "travel",
    icon: "✈️",
    subcategories: [
      { name: "מלונות", name_en: "hotels", slug: "hotels" },
      { name: "צימרים", name_en: "bnb", slug: "bnb" },
      { name: "סוכנויות נסיעות", name_en: "travel-agencies", slug: "travel-agencies" },
      { name: "השכרת רכב", name_en: "rental-cars", slug: "rental-cars" },
      { name: "מדריכי טיולים", name_en: "tour-guides", slug: "tour-guides" },
    ],
  },
  {
    name: "טכנולוגיה ומחשבים",
    name_en: "technology",
    slug: "technology",
    icon: "💻",
    subcategories: [
      { name: "תיקון מחשבים", name_en: "computer-repair", slug: "computer-repair" },
      { name: "פיתוח אתרים", name_en: "web-dev", slug: "web-dev" },
      { name: "תיקון סלולר", name_en: "phone-repair", slug: "phone-repair" },
      { name: "שירותי IT", name_en: "it-services", slug: "it-services" },
      { name: "אבטחת מידע", name_en: "cybersecurity", slug: "cybersecurity" },
    ],
  },
  {
    name: "תחבורה",
    name_en: "transport",
    slug: "transport",
    icon: "🚌",
    subcategories: [
      { name: "מוניות", name_en: "taxis", slug: "taxis" },
      { name: "הסעות", name_en: "shuttles", slug: "shuttles" },
      { name: "שליחויות", name_en: "couriers", slug: "couriers" },
      { name: "הובלות", name_en: "freight", slug: "freight" },
    ],
  },
  {
    name: "דת ורוחניות",
    name_en: "religion",
    slug: "religion",
    icon: "🕍",
    subcategories: [
      { name: "בתי כנסת", name_en: "synagogues", slug: "synagogues" },
      { name: "מסגדים", name_en: "mosques", slug: "mosques" },
      { name: "כנסיות", name_en: "churches", slug: "churches" },
      { name: "מקוואות", name_en: "mikvahs", slug: "mikvahs" },
      { name: "יודאיקה", name_en: "judaica", slug: "judaica" },
    ],
  },
  {
    name: "ממשל ושירותים ציבוריים",
    name_en: "government",
    slug: "government",
    icon: "🏛️",
    subcategories: [
      { name: "עיריות ומועצות", name_en: "municipalities", slug: "municipalities" },
      { name: "משרדי ממשלה", name_en: "gov-offices", slug: "gov-offices" },
      { name: "דואר", name_en: "post", slug: "post" },
      { name: "בנקים", name_en: "banks", slug: "banks" },
      { name: "ביטוח לאומי", name_en: "national-insurance", slug: "national-insurance" },
    ],
  },
] as const;

export const CITIES = [
  "תל אביב-יפו", "ירושלים", "חיפה", "באר שבע", "ראשון לציון",
  "פתח תקוה", "אשדוד", "נתניה", "חולון", "בני ברק",
  "רמת גן", "אשקלון", "בת ים", "הרצליה", "כפר סבא",
  "רעננה", "מודיעין", "לוד", "רמלה", "נצרת",
  "עכו", "אילת", "טבריה", "צפת", "קרית שמונה",
  "נהריה", "עפולה", "קרית אתא", "קרית ביאליק", "קרית ים",
  "קרית מוצקין", "רחובות", "נס ציונה", "הוד השרון", "רמת השרון",
  "גבעתיים", "יבנה", "אור יהודה", "קרית גת", "דימונה",
  "ערד", "מצפה רמון", "כרמיאל", "יקנעם", "מגדל העמק",
  "אום אל-פחם", "סח'נין", "טמרה", "שפרעם", "באקה אל-גרבייה",
] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];
